name: Checkov IaC Scan

on: workflow_dispatch

jobs:
  checkov_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Checkov
      run: pip3 install checkov

    - name: Run Checkov
      run: checkov -d .
